### ISSUE TITLE
mission.sqm mismatch with steam workshop

### ISSUE THREAD

**Issue by willwagner602** [TMNFr33d0m/A3M-PMC-Simulator#4]
I'm not sure why this is, but mission.sqm in the repo doesn't match the one in steam workshop - functionally, it doesn't contain the Alive logic objects (there may be other things mismatched between the two, I didn't do an exhaustive search). It is also ~23KB smaller than in the .pbo delivered through steam workshop.

**Comment by TMNFr33d0m** [comment]
Ohh yeah, that's not a "pre-release build" tho, That's the most recent sync I did on the WIP version, and I pull out the core ALiVE Modules when I work, so that the load times aren't insane while I'm loading and reloading to test stuff. :-D 

I leave the file structure open to the public so that A) They can contribute! B) They can see progress in real time, and advanced users can update modularly, and C) so ppl can copy my work, and make their own versions from it!

The steam version is a "Pre-Release" build, and is designed to be playable. The same version is hosted on this GitHub. Each time I get ready to release a build, i'll put the ALiVE modules down, build a PBO and publish it. Between the releases tho, the WIP file structure is likely to be a lot like a car in the shop with the engine ripped open. 

Thanks for the very attentive report!

**Comment by willwagner602** [comment]
Gotcha - I figured it might be intentional, Alive does take literally forever!
