### ISSUE TITLE
Checkpoint mission not working.

### ISSUE THREAD

**Issue by CapnFruitloops** [TMNFr33d0m/A3M-PMC-Simulator#9]
Playing the mission with my unit recently and the checkpoint mission will not work. I can click on all the others and request them and I get the notification and the mission starts, but with the checkpoint mission, nothing seems to happen.

**Comment by CapnFruitloops** [comment]
Hey, just curious if I could get the fixed version once you track down the issue, my unit really enjoys this mission in our downtime and the checkpoint contract is one of their favorites.

**Comment by TMNFr33d0m** [comment]
Absolutely! Just a heads up, we are already out of mission format, next
update will convert to a mod format. Problem does not exist on non-dedi
server, so problem is broken locality on dedi server. Will attempt to fix
and push new mod to you in next 48 hrs.

Thanks for the serious bug report.

On Sunday, August 23, 2015, captainloper notifications@github.com wrote:

> Hey, just curious if I could get the fixed version once you track down the
> issue, my unit really enjoys this mission in our downtime and the
> checkpoint contract is one of their favorites.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TMNFr33d0m/A3M-PMC-Simulator/issues/9#issuecomment-133811957
> .

## 

Cody J. Salazar-Betzer
Personal E-mail (G-mail)
FOR PERSONAL USE ONLY!

**Comment by SGTGunner** [comment]
Will there is a script only version as well. Or is everything going to a mod format? Going to a mod format will mean everyone will need the mod, right? Which is a pain. Thanks.

**Comment by TMNFr33d0m** [comment]
Yes, in order to really do what I wanted with this mode, I had to turn it
into a mod that every machine including the server needs to run. Just spent
the last three days converting everything. I will be hosting it on PWS, my
website and releasing on all normal major avenues when I release it.

In the mod version, you will see enhanced performance, smaller mission file
size (it was pushing 20mb, as you probably know), brand new custom object
models, and a greatly enhanced gameplay experience.

I hope you can endure the pain of yet another mod to enjoy the great new
things I have in store!

On Sunday, August 23, 2015, WSIContractor notifications@github.com wrote:

> Will there is a script only version as well. Or is everything going to a
> mod format? Going to a mod format will mean everyone will need the mod,
> right? Which is a pain. Thanks.
> 
> —M
> Reply to this email directly or view it on GitHub
> https://github.com/TMNFr33d0m/A3M-PMC-Simulator/issues/9#issuecomment-133897640
> .

## 

Cody J. Salazar-Betzer
Personal E-mail (G-mail)
FOR PERSONAL USE ONLY!

**Comment by TMNFr33d0m** [comment]
Okay, Since I have 1luv for ArmA community and those that play my mode, I went ahead and made a retroactive version. This one is still in mission format, NOT mod format.

Fixes and new additions, in mission format!!! Ok, really, last version in mission format. We're going to mod version now! 

https://github.com/TMNFr33d0m/A3M-PMC-Simulator/releases/tag/0.3.1
